[dev] ctl + cloud - run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -13,6 +13,26 @@ function error {
 vars_file_shell="$1/vars.sh"
 vars_file_yaml="$1/vars.yml"
 
+shift;
+
+debug=()
+
+# shellcheck disable=SC2214
+while getopts ':f-:' OPT; do
+	if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
+		OPT="${OPTARG%%=*}"       # extract long option name
+		OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+		OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+	fi
+	case "$OPT" in
+		f|fast ) fast="true"; args+=( "--fast" );;
+		debug ) debug=( "-vvvvv" );;
+		??* ) break;;  # long option
+		\? )  break;;  # short option
+	esac
+done
+shift $((OPTIND-1))
+
 #shellcheck disable=SC1090
 . "$vars_file_shell"
 
@@ -31,11 +51,13 @@ fi
 var_repo_dir="$repo_dir"
 cd "$var_repo_dir"
 
-if [ "${arg_fast:-}" = 'true' ]; then
+if [ "${fast:-}" = 'true' ]; then
 	echo "[cloud] skipping prepare project context (fast)..."
 else
 	# Prepare the cloud context
-	ansible-playbook ${vault[@]+"${vault[@]}"} \
+	ansible-playbook \
+		${vault[@]+"${vault[@]}"} \
+		${debug[@]+"${debug[@]}"} \
 		-i hosts \
 		-e env_vars_file="$vars_file_yaml" \
         prepare.ctx.yml || error "[error] prepare ctx"
@@ -45,7 +67,9 @@ fi
 var_ctx_dir="$ctx_dir"
 
 # Execute the cloud context
-ansible-playbook ${vault[@]+"${vault[@]}"} \
+ansible-playbook \
+	${vault[@]+"${vault[@]}"} \
+	${debug[@]+"${debug[@]}"} \
 	-i "$var_ctx_dir/hosts" \
 	-e env_vars_file="$vars_file_yaml" \
-    main.yml || error "[error] run ctx"
+    main.yml "${@}" || error "[error] run ctx"
